# Generated by Django 6.0.2 on 2026-02-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان العقار')),
                ('property_type', models.CharField(choices=[('villa', 'فيلا'), ('apartment', 'شقة'), ('land', 'أرض'), ('building', 'عمارة')], max_length=20, verbose_name='نوع العقار')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='السعر')),
                ('area', models.IntegerField(verbose_name='المساحة (متر مربع)')),
                ('district', models.CharField(max_length=100, verbose_name='الحي')),
                ('description', models.TextField(verbose_name='وصف العقار')),
                ('main_image', models.ImageField(upload_to='properties/', verbose_name='الصورة الرئيسية')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'عقار',
                'verbose_name_plural': 'العقارات',
            },
        ),
    ]
