# Generated by Django 6.0.2 on 2026-02-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='bathrooms',
            field=models.IntegerField(default=0, verbose_name='عدد دورات المياه'),
        ),
        migrations.AddField(
            model_name='property',
            name='offer_type',
            field=models.CharField(choices=[('بيع', 'بيع'), ('إيجار', 'إيجار')], default='بيع', max_length=10, verbose_name='نوع العرض'),
        ),
        migrations.AddField(
            model_name='property',
            name='rooms',
            field=models.IntegerField(default=0, verbose_name='عدد الغرف'),
        ),
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('متاح', 'متاح'), ('مباع', 'مباع'), ('تحت الإجراء', 'تحت الإجراء')], default='متاح', max_length=20, verbose_name='حالة العقار'),
        ),
    ]
