# Generated by Django 6.0.2 on 2026-02-11 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_property_bathrooms_property_offer_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('متاح', 'متاح'), ('مؤجر', 'مؤجر'), ('تحت الإجراء', 'تحت الإجراء'), ('مباع', 'مباع')], default='متاح', max_length=20, verbose_name='حالة العقار'),
        ),
    ]
