# Generated by Django 6.0.2 on 2026-02-12 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_property_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='bathrooms',
        ),
        migrations.RemoveField(
            model_name='property',
            name='description',
        ),
        migrations.RemoveField(
            model_name='property',
            name='district',
        ),
        migrations.RemoveField(
            model_name='property',
            name='main_image',
        ),
        migrations.RemoveField(
            model_name='property',
            name='rooms',
        ),
        migrations.RemoveField(
            model_name='property',
            name='status',
        ),
        migrations.RemoveField(
            model_name='property',
            name='title',
        ),
        migrations.AddField(
            model_name='property',
            name='floors',
            field=models.IntegerField(blank=True, null=True, verbose_name='عدد الأدوار'),
        ),
        migrations.AddField(
            model_name='property',
            name='full_name',
            field=models.CharField(default='جودة المستقبل', max_length=255, verbose_name='اسم المالك بالكامل'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='phone',
            field=models.CharField(default='0548129909', max_length=20, verbose_name='رقم الجوال'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='photos_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='رابط الصور'),
        ),
        migrations.AddField(
            model_name='property',
            name='property_age',
            field=models.IntegerField(blank=True, null=True, verbose_name='عمر العقار'),
        ),
        migrations.AddField(
            model_name='property',
            name='rooms_or_apartments',
            field=models.IntegerField(blank=True, null=True, verbose_name='عدد الغرف / الشقق'),
        ),
        migrations.AddField(
            model_name='property',
            name='usage_type',
            field=models.CharField(blank=True, choices=[('سكني', 'سكني'), ('تجاري', 'تجاري')], max_length=20, null=True, verbose_name='الاستخدام'),
        ),
        migrations.AlterField(
            model_name='property',
            name='area',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المساحة'),
        ),
        migrations.AlterField(
            model_name='property',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة'),
        ),
        migrations.AlterField(
            model_name='property',
            name='offer_type',
            field=models.CharField(choices=[('بيع', 'بيع'), ('إيجار', 'إيجار')], max_length=20, verbose_name='نوع العرض'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='السعر المتوقع'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('فيلا', 'فيلا'), ('شقة', 'شقة'), ('عمارة', 'عمارة'), ('دور', 'دور'), ('أرض', 'أرض'), ('مزرعة', 'مزرعة'), ('استراحة', 'استراحة'), ('محل تجاري', 'محل تجاري')], max_length=50, verbose_name='نوع العقار'),
        ),
    ]
