# Generated by Django 6.0 on 2026-02-12 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_remove_property_bathrooms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='bathrooms',
            field=models.IntegerField(blank=True, null=True, verbose_name='عدد دورات المياه'),
        ),
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.CharField(default='الرياض', max_length=50, verbose_name='المدينة'),
        ),
        migrations.AddField(
            model_name='property',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الحي'),
        ),
    ]
