# Generated by Django 6.0 on 2026-02-12 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_property_bathrooms_property_city_property_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='rooms_or_apartments',
        ),
        migrations.AddField(
            model_name='property',
            name='apartments',
            field=models.IntegerField(blank=True, null=True, verbose_name='عدد الشقق'),
        ),
        migrations.AddField(
            model_name='property',
            name='rooms',
            field=models.IntegerField(blank=True, null=True, verbose_name='عدد الغرف'),
        ),
    ]
