# Generated by Django 6.0 on 2026-02-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_remove_property_rooms_or_apartments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='listing_id',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True, verbose_name='رقم العرض'),
        ),
        migrations.AlterField(
            model_name='property',
            name='area',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المساحة (م²)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='usage_type',
            field=models.CharField(blank=True, choices=[('سكني', 'سكني'), ('تجاري', 'تجاري')], max_length=20, null=True, verbose_name='نوع الاستخدام'),
        ),
    ]
