# Generated by Django 6.0 on 2026-02-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_property_listing_id_alter_property_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='inquiry_count',
            field=models.IntegerField(default=0, verbose_name='عدد الاستفسارات'),
        ),
    ]
