# Generated by Django 6.0.2 on 2026-02-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_property_inquiry_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='photos_url',
        ),
        migrations.AddField(
            model_name='property',
            name='image1',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='صورة 1'),
        ),
        migrations.AddField(
            model_name='property',
            name='image10',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='صورة 10'),
        ),
        migrations.AddField(
            model_name='property',
            name='image2',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='صورة 2'),
        ),
        migrations.AddField(
            model_name='property',
            name='image3',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='صورة 3'),
        ),
        migrations.AddField(
            model_name='property',
            name='image4',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='صورة 4'),
        ),
        migrations.AddField(
            model_name='property',
            name='image5',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='صورة 5'),
        ),
        migrations.AddField(
            model_name='property',
            name='image6',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='صورة 6'),
        ),
        migrations.AddField(
            model_name='property',
            name='image7',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='صورة 7'),
        ),
        migrations.AddField(
            model_name='property',
            name='image8',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='صورة 8'),
        ),
        migrations.AddField(
            model_name='property',
            name='image9',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='صورة 9'),
        ),
    ]
