# Generated by Django 6.0 on 2026-02-12 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_remove_property_photos_url_property_image1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='admin_notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات الإدارة'),
        ),
        migrations.AddField(
            model_name='property',
            name='map_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='رابط الموقع (قوقل ماب)'),
        ),
        migrations.AddField(
            model_name='property',
            name='owner_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم صاحب العقار'),
        ),
        migrations.AddField(
            model_name='property',
            name='owner_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='جوال صاحب العقار'),
        ),
    ]
