# Generated by Django 6.0 on 2026-02-12 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_property_admin_notes_property_map_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('متاح', 'متاح'), ('مباع', 'مباع'), ('مؤجر', 'مؤجر')], default='متاح', max_length=20, verbose_name='حالة العقار'),
        ),
    ]
