# Generated by Django 6.0 on 2026-02-12 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_property_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/', verbose_name='صورة 1'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image10',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/', verbose_name='صورة 10'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/', verbose_name='صورة 2'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/', verbose_name='صورة 3'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/', verbose_name='صورة 4'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/', verbose_name='صورة 5'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/', verbose_name='صورة 6'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image7',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/', verbose_name='صورة 7'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image8',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/', verbose_name='صورة 8'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image9',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/', verbose_name='صورة 9'),
        ),
    ]
