# Generated by Django 6.0.2 on 2026-02-12 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_alter_property_image1_alter_property_image10_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='owner_name',
        ),
        migrations.RemoveField(
            model_name='property',
            name='owner_phone',
        ),
        migrations.AlterField(
            model_name='property',
            name='listing_id',
            field=models.CharField(default='0', editable=False, max_length=10, unique=True, verbose_name='رقم العرض'),
            preserve_default=False,
        ),
    ]
