# Generated by Django 6.0 on 2026-02-12 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_remove_property_owner_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='listing_id',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True, unique=True, verbose_name='رقم العرض'),
        ),
    ]
