# Generated by Django 6.0.2 on 2026-02-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_alter_property_listing_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='admin_notes',
            field=models.TextField(blank=True, null=True, verbose_name='وصف العقار'),
        ),
    ]
