# Generated by Django 6.0.2 on 2026-02-13 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0015_alter_property_admin_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='admin_notes',
            field=models.CharField(blank=True, max_length=180, null=True, verbose_name='وصف العقار'),
        ),
    ]
