# Generated by Django 6.0.2 on 2026-02-13 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0016_alter_property_admin_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='usage_type',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='admin_notes',
            new_name='owner_notes',
        ),
    ]
