# Generated by Django 6.0.2 on 2026-02-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0017_rename_usage_type_property_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=255, verbose_name='اسم المالك')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الجوال')),
                ('whatsapp_url', models.URLField(max_length=500, verbose_name='رابط واتساب')),
                ('city', models.CharField(max_length=50, verbose_name='المدينة')),
                ('neighborhood', models.CharField(max_length=100, verbose_name='الحي')),
                ('property_type', models.CharField(max_length=50, verbose_name='نوع العقار')),
                ('property_age', models.CharField(blank=True, max_length=50, null=True, verbose_name='عمر العقار')),
                ('listing_type', models.CharField(max_length=20, verbose_name='نوع العرض')),
                ('category', models.CharField(max_length=20, verbose_name='نوع الاستخدام')),
                ('area', models.CharField(max_length=50, verbose_name='المساحة')),
                ('price', models.CharField(max_length=50, verbose_name='السعر')),
                ('floors', models.IntegerField(default=0, verbose_name='عدد الأدوار')),
                ('apartments', models.IntegerField(default=0, verbose_name='عدد الشقق')),
                ('rooms', models.IntegerField(default=0, verbose_name='عدد الغرف')),
                ('bathrooms', models.IntegerField(default=0, verbose_name='عدد دورات المياه')),
                ('images_link', models.URLField(max_length=500, verbose_name='رابط الصور (Drive)')),
                ('google_map', models.URLField(blank=True, max_length=500, null=True, verbose_name='رابط الموقع')),
                ('owner_notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات المالك')),
                ('status', models.CharField(choices=[('جديد', 'جديد'), ('قيد المراجعة', 'قيد المراجعة'), ('تم النشر', 'تم النشر'), ('مرفوض', 'مرفوض')], default='جديد', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
            ],
            options={
                'verbose_name': 'طلب عرض عقار',
                'verbose_name_plural': 'طلبات عروض العقارات',
            },
        ),
    ]
