# Generated by Django 6.0.2 on 2026-02-14 17:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0018_propertylead'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=255, verbose_name='اسم المالك')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الجوال')),
                ('whatsapp_url', models.URLField(max_length=500, verbose_name='رابط واتساب')),
                ('city', models.CharField(max_length=50, verbose_name='المدينة')),
                ('neighborhood', models.CharField(max_length=100, verbose_name='الحي')),
                ('property_type', models.CharField(max_length=50, verbose_name='نوع العقار')),
                ('property_age', models.CharField(blank=True, max_length=50, null=True, verbose_name='عمر العقار')),
                ('listing_type', models.CharField(max_length=20, verbose_name='نوع العرض')),
                ('category', models.CharField(max_length=20, verbose_name='نوع الاستخدام')),
                ('area', models.CharField(max_length=50, verbose_name='المساحة')),
                ('price', models.CharField(max_length=50, verbose_name='السعر')),
                ('floors', models.IntegerField(default=0, verbose_name='عدد الأدوار')),
                ('apartments', models.IntegerField(default=0, verbose_name='عدد الشقق')),
                ('rooms', models.IntegerField(default=0, verbose_name='عدد الغرف')),
                ('bathrooms', models.IntegerField(default=0, verbose_name='عدد دورات المياه')),
                ('images_link', models.URLField(max_length=500, verbose_name='رابط الصور (Drive)')),
                ('google_map', models.URLField(blank=True, max_length=500, null=True, verbose_name='رابط الموقع')),
                ('owner_notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات المالك')),
                ('status', models.CharField(choices=[('جديد', 'جديد'), ('قيد المراجعة', 'قيد المراجعة'), ('تم النشر', 'تم النشر'), ('مرفوض', 'مرفوض')], default='جديد', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
            ],
            options={
                'verbose_name': 'طلب عرض عقار',
                'verbose_name_plural': 'طلبات عروض العقارات',
            },
        ),
        migrations.AlterModelOptions(
            name='propertylead',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='propertylead',
            name='apartments',
        ),
        migrations.RemoveField(
            model_name='propertylead',
            name='area',
        ),
        migrations.RemoveField(
            model_name='propertylead',
            name='bathrooms',
        ),
        migrations.RemoveField(
            model_name='propertylead',
            name='category',
        ),
        migrations.RemoveField(
            model_name='propertylead',
            name='city',
        ),
        migrations.RemoveField(
            model_name='propertylead',
            name='floors',
        ),
        migrations.RemoveField(
            model_name='propertylead',
            name='google_map',
        ),
        migrations.RemoveField(
            model_name='propertylead',
            name='images_link',
        ),
        migrations.RemoveField(
            model_name='propertylead',
            name='listing_type',
        ),
        migrations.RemoveField(
            model_name='propertylead',
            name='neighborhood',
        ),
        migrations.RemoveField(
            model_name='propertylead',
            name='owner_name',
        ),
        migrations.RemoveField(
            model_name='propertylead',
            name='owner_notes',
        ),
        migrations.RemoveField(
            model_name='propertylead',
            name='price',
        ),
        migrations.RemoveField(
            model_name='propertylead',
            name='property_age',
        ),
        migrations.RemoveField(
            model_name='propertylead',
            name='property_type',
        ),
        migrations.RemoveField(
            model_name='propertylead',
            name='rooms',
        ),
        migrations.RemoveField(
            model_name='propertylead',
            name='status',
        ),
        migrations.RemoveField(
            model_name='propertylead',
            name='whatsapp_url',
        ),
        migrations.AddField(
            model_name='propertylead',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertylead',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertylead',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='propertylead',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='listings.property'),
        ),
        migrations.AddField(
            model_name='propertylead',
            name='source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='propertylead',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='propertylead',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
