# Generated by Django 6.0.2 on 2026-02-17 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0019_propertyoffer_alter_propertylead_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyoffer',
            name='video_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='رابط فيديو (يوتيوب/تيك توك)'),
        ),
        migrations.CreateModel(
            name='PropertyRequestImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_requests/', verbose_name='الصورة')),
                ('is_cover', models.BooleanField(default=False, verbose_name='صورة الغلاف')),
                ('sort_order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.propertyoffer')),
            ],
            options={
                'verbose_name': 'صورة طلب عقار',
                'verbose_name_plural': 'صور طلبات العقارات',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
    ]
