# Generated by Django 6.0.2 on 2026-02-17 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0020_propertyoffer_video_link_propertyrequestimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='show_map_to_visitors',
            field=models.BooleanField(default=False, help_text='إظهار/إخفاء موقع العقار للزوار (يعتمد أيضًا على وجود map_url).'),
        ),
    ]
