# Generated by Django 6.0.2 on 2026-02-17 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0021_property_show_map_to_visitors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyoffer',
            name='apartments',
        ),
        migrations.RemoveField(
            model_name='propertyoffer',
            name='area',
        ),
        migrations.RemoveField(
            model_name='propertyoffer',
            name='bathrooms',
        ),
        migrations.RemoveField(
            model_name='propertyoffer',
            name='category',
        ),
        migrations.RemoveField(
            model_name='propertyoffer',
            name='city',
        ),
        migrations.RemoveField(
            model_name='propertyoffer',
            name='floors',
        ),
        migrations.RemoveField(
            model_name='propertyoffer',
            name='google_map',
        ),
        migrations.RemoveField(
            model_name='propertyoffer',
            name='images_link',
        ),
        migrations.RemoveField(
            model_name='propertyoffer',
            name='listing_type',
        ),
        migrations.RemoveField(
            model_name='propertyoffer',
            name='neighborhood',
        ),
        migrations.RemoveField(
            model_name='propertyoffer',
            name='owner_name',
        ),
        migrations.RemoveField(
            model_name='propertyoffer',
            name='owner_notes',
        ),
        migrations.RemoveField(
            model_name='propertyoffer',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='propertyoffer',
            name='price',
        ),
        migrations.RemoveField(
            model_name='propertyoffer',
            name='property_age',
        ),
        migrations.RemoveField(
            model_name='propertyoffer',
            name='property_type',
        ),
        migrations.RemoveField(
            model_name='propertyoffer',
            name='rooms',
        ),
        migrations.RemoveField(
            model_name='propertyoffer',
            name='video_link',
        ),
        migrations.RemoveField(
            model_name='propertyoffer',
            name='whatsapp_url',
        ),
        migrations.AddField(
            model_name='property',
            name='source_offer',
            field=models.OneToOneField(blank=True, help_text='الطلب الذي تم تحويله إلى هذا العقار (للتتبع ومنع التكرار).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_property', to='listings.propertyoffer'),
        ),
        migrations.AlterField(
            model_name='propertyoffer',
            name='status',
            field=models.CharField(choices=[('new', 'جديد'), ('under_review', 'قيد المراجعة'), ('approved', 'مقبول'), ('rejected', 'مرفوض'), ('published', 'تم نشره')], db_index=True, default='new', max_length=20, verbose_name='الحالة'),
        ),
    ]
