# Generated by Django 6.0.2 on 2026-02-17 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0022_remove_propertyoffer_apartments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyoffer',
            name='apartments',
            field=models.IntegerField(default=0, verbose_name='عدد الشقق'),
        ),
        migrations.AddField(
            model_name='propertyoffer',
            name='area',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='المساحة'),
        ),
        migrations.AddField(
            model_name='propertyoffer',
            name='bathrooms',
            field=models.IntegerField(default=0, verbose_name='عدد دورات المياه'),
        ),
        migrations.AddField(
            model_name='propertyoffer',
            name='category',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='نوع الاستخدام'),
        ),
        migrations.AddField(
            model_name='propertyoffer',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='المدينة'),
        ),
        migrations.AddField(
            model_name='propertyoffer',
            name='floors',
            field=models.IntegerField(default=0, verbose_name='عدد الأدوار'),
        ),
        migrations.AddField(
            model_name='propertyoffer',
            name='google_map',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='رابط الموقع'),
        ),
        migrations.AddField(
            model_name='propertyoffer',
            name='images_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='رابط الصور (Drive)'),
        ),
        migrations.AddField(
            model_name='propertyoffer',
            name='listing_type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='نوع العرض'),
        ),
        migrations.AddField(
            model_name='propertyoffer',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الحي'),
        ),
        migrations.AddField(
            model_name='propertyoffer',
            name='owner_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم المالك'),
        ),
        migrations.AddField(
            model_name='propertyoffer',
            name='owner_notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات المالك'),
        ),
        migrations.AddField(
            model_name='propertyoffer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الجوال'),
        ),
        migrations.AddField(
            model_name='propertyoffer',
            name='price',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='السعر'),
        ),
        migrations.AddField(
            model_name='propertyoffer',
            name='property_age',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='عمر العقار'),
        ),
        migrations.AddField(
            model_name='propertyoffer',
            name='property_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع العقار'),
        ),
        migrations.AddField(
            model_name='propertyoffer',
            name='rooms',
            field=models.IntegerField(default=0, verbose_name='عدد الغرف'),
        ),
        migrations.AddField(
            model_name='propertyoffer',
            name='video_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='رابط فيديو (يوتيوب/تيك توك)'),
        ),
        migrations.AddField(
            model_name='propertyoffer',
            name='whatsapp_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='رابط واتساب'),
        ),
    ]
