# Generated by Django 6.0.2 on 2026-02-19 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0023_propertyoffer_apartments_propertyoffer_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('متاح', 'متاح'), ('مباع', 'مباع'), ('مؤجر', 'مؤجر'), ('مخفي', 'مخفي')], default='متاح', max_length=20, verbose_name='حالة العقار'),
        ),
    ]
