# Generated by Django 6.0.2 on 2026-02-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0024_alter_property_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='visibility',
            field=models.CharField(choices=[('منشور', 'منشور'), ('مخفي', 'مخفي')], default='منشور', max_length=20, verbose_name='حالة العرض'),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('متاح', 'متاح'), ('مباع', 'مباع'), ('مؤجر', 'مؤجر')], default='متاح', max_length=20, verbose_name='حالة العقار'),
        ),
    ]
