# Generated by Django 6.0.2 on 2026-02-22 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0025_property_visibility_alter_property_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='السعر المتوقع'),
        ),
    ]
