# Generated by Django 6.0.2 on 2026-02-22 22:54

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0026_alter_property_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image1',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='صورة 1'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image10',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='صورة 10'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image2',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='صورة 2'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image3',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='صورة 3'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image4',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='صورة 4'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image5',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='صورة 5'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image6',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='صورة 6'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image7',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='صورة 7'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image8',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='صورة 8'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image9',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='صورة 9'),
        ),
        migrations.AlterField(
            model_name='propertyrequestimage',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='الصورة'),
        ),
    ]
