# Generated by Django 6.0.2 on 2026-02-26 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0027_alter_property_image1_alter_property_image10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='map_url',
            field=models.TextField(blank=True, null=True, verbose_name='رابط الموقع (قوقل ماب)'),
        ),
        migrations.AlterField(
            model_name='propertyoffer',
            name='google_map',
            field=models.TextField(blank=True, null=True, verbose_name='رابط الموقع'),
        ),
        migrations.AlterField(
            model_name='propertyoffer',
            name='images_link',
            field=models.TextField(blank=True, null=True, verbose_name='رابط الصور (Drive)'),
        ),
        migrations.AlterField(
            model_name='propertyoffer',
            name='video_link',
            field=models.TextField(blank=True, null=True, verbose_name='رابط فيديو (يوتيوب/تيك توك)'),
        ),
        migrations.AlterField(
            model_name='propertyoffer',
            name='whatsapp_url',
            field=models.TextField(blank=True, null=True, verbose_name='رابط واتساب'),
        ),
    ]
