# Generated by Django 6.0.2 on 2026-02-26 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0028_alter_property_map_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={},
        ),
        migrations.AlterModelOptions(
            name='propertyoffer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='propertyrequestimage',
            options={'ordering': ['sort_order', 'created_at']},
        ),
        migrations.AlterField(
            model_name='property',
            name='apartments',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='area',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='bathrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='category',
            field=models.CharField(blank=True, choices=[('سكني', 'سكني'), ('تجاري', 'تجاري')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(default='الرياض', max_length=50),
        ),
        migrations.AlterField(
            model_name='property',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='floors',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='inquiry_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='map_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='offer_type',
            field=models.CharField(choices=[('بيع', 'بيع'), ('إيجار', 'إيجار')], max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='owner_notes',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('فيلا', 'فيلا'), ('شقة', 'شقة'), ('عمارة', 'عمارة'), ('دور', 'دور'), ('أرض', 'أرض'), ('مزرعة', 'مزرعة'), ('استراحة', 'استراحة'), ('محل تجاري', 'محل تجاري')], max_length=50),
        ),
        migrations.AlterField(
            model_name='property',
            name='rooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='show_map_to_visitors',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='source_offer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_property', to='listings.propertyoffer'),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('متاح', 'متاح'), ('مباع', 'مباع'), ('مؤجر', 'مؤجر')], default='متاح', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='visibility',
            field=models.CharField(choices=[('منشور', 'منشور'), ('مخفي', 'مخفي')], default='منشور', max_length=20),
        ),
        migrations.AlterField(
            model_name='propertyoffer',
            name='apartments',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='propertyoffer',
            name='area',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='propertyoffer',
            name='bathrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='propertyoffer',
            name='category',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='propertyoffer',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='propertyoffer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='propertyoffer',
            name='floors',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='propertyoffer',
            name='google_map',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertyoffer',
            name='images_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertyoffer',
            name='listing_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='propertyoffer',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propertyoffer',
            name='owner_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='propertyoffer',
            name='owner_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertyoffer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='propertyoffer',
            name='price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='propertyoffer',
            name='property_age',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='propertyoffer',
            name='property_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='propertyoffer',
            name='rooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='propertyoffer',
            name='status',
            field=models.CharField(default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='propertyoffer',
            name='video_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertyoffer',
            name='whatsapp_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertyrequestimage',
            name='is_cover',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='propertyrequestimage',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
