# Generated by Django 6.0.2 on 2026-02-26 20:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0029_alter_property_options_alter_propertyoffer_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': 'عقار', 'verbose_name_plural': 'العقارات'},
        ),
        migrations.AlterModelOptions(
            name='propertylead',
            options={'ordering': ['-created_at'], 'verbose_name': 'عميل محتمل', 'verbose_name_plural': 'العملاء المحتملين'},
        ),
        migrations.AlterModelOptions(
            name='propertyoffer',
            options={'verbose_name': 'طلب تسويق عقار', 'verbose_name_plural': 'طلبات تسويق العقارات'},
        ),
        migrations.AlterModelOptions(
            name='propertyrequestimage',
            options={'ordering': ['sort_order', 'created_at'], 'verbose_name': 'صورة طلب عقار', 'verbose_name_plural': 'صور طلبات العقارات'},
        ),
        migrations.AlterField(
            model_name='property',
            name='apartments',
            field=models.IntegerField(blank=True, null=True, verbose_name='عدد الشقق'),
        ),
        migrations.AlterField(
            model_name='property',
            name='area',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المساحة'),
        ),
        migrations.AlterField(
            model_name='property',
            name='bathrooms',
            field=models.IntegerField(blank=True, null=True, verbose_name='عدد دورات المياه'),
        ),
        migrations.AlterField(
            model_name='property',
            name='category',
            field=models.CharField(blank=True, choices=[('سكني', 'سكني'), ('تجاري', 'تجاري')], max_length=20, null=True, verbose_name='التصنيف'),
        ),
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(default='الرياض', max_length=50, verbose_name='المدينة'),
        ),
        migrations.AlterField(
            model_name='property',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة'),
        ),
        migrations.AlterField(
            model_name='property',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الحي'),
        ),
        migrations.AlterField(
            model_name='property',
            name='floors',
            field=models.IntegerField(blank=True, null=True, verbose_name='عدد الأدوار'),
        ),
        migrations.AlterField(
            model_name='property',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='الاسم الكامل'),
        ),
        migrations.AlterField(
            model_name='property',
            name='inquiry_count',
            field=models.IntegerField(default=0, verbose_name='عدد الاستفسارات'),
        ),
        migrations.AlterField(
            model_name='property',
            name='listing_id',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True, unique=True, verbose_name='رقم العقار'),
        ),
        migrations.AlterField(
            model_name='property',
            name='map_url',
            field=models.TextField(blank=True, null=True, verbose_name='رابط الخريطة'),
        ),
        migrations.AlterField(
            model_name='property',
            name='offer_type',
            field=models.CharField(choices=[('بيع', 'بيع'), ('إيجار', 'إيجار')], max_length=20, verbose_name='نوع العرض'),
        ),
        migrations.AlterField(
            model_name='property',
            name='owner_notes',
            field=models.CharField(blank=True, max_length=180, null=True, verbose_name='ملاحظات المالك'),
        ),
        migrations.AlterField(
            model_name='property',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='رقم الجوال'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='السعر'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_age',
            field=models.IntegerField(blank=True, null=True, verbose_name='عمر العقار'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('فيلا', 'فيلا'), ('شقة', 'شقة'), ('عمارة', 'عمارة'), ('دور', 'دور'), ('أرض', 'أرض'), ('مزرعة', 'مزرعة'), ('استراحة', 'استراحة'), ('محل تجاري', 'محل تجاري')], max_length=50, verbose_name='نوع العقار'),
        ),
        migrations.AlterField(
            model_name='property',
            name='rooms',
            field=models.IntegerField(blank=True, null=True, verbose_name='عدد الغرف'),
        ),
        migrations.AlterField(
            model_name='property',
            name='show_map_to_visitors',
            field=models.BooleanField(default=False, verbose_name='إظهار الخريطة للزوار'),
        ),
        migrations.AlterField(
            model_name='property',
            name='source_offer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_property', to='listings.propertyoffer', verbose_name='الطلب المصدر'),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('متاح', 'متاح'), ('مباع', 'مباع'), ('مؤجر', 'مؤجر')], default='متاح', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='property',
            name='visibility',
            field=models.CharField(choices=[('منشور', 'منشور'), ('مخفي', 'مخفي')], default='منشور', max_length=20, verbose_name='حالة الظهور'),
        ),
        migrations.AlterField(
            model_name='propertylead',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الطلب'),
        ),
        migrations.AlterField(
            model_name='propertylead',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP'),
        ),
        migrations.AlterField(
            model_name='propertylead',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='الرسالة'),
        ),
        migrations.AlterField(
            model_name='propertylead',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='propertylead',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الجوال'),
        ),
        migrations.AlterField(
            model_name='propertylead',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='listings.property', verbose_name='العقار'),
        ),
        migrations.AlterField(
            model_name='propertylead',
            name='source',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='المصدر'),
        ),
        migrations.AlterField(
            model_name='propertyoffer',
            name='apartments',
            field=models.IntegerField(default=0, verbose_name='عدد الشقق'),
        ),
        migrations.AlterField(
            model_name='propertyoffer',
            name='area',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='المساحة'),
        ),
        migrations.AlterField(
            model_name='propertyoffer',
            name='bathrooms',
            field=models.IntegerField(default=0, verbose_name='عدد دورات المياه'),
        ),
        migrations.AlterField(
            model_name='propertyoffer',
            name='category',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='التصنيف'),
        ),
        migrations.AlterField(
            model_name='propertyoffer',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='المدينة'),
        ),
        migrations.AlterField(
            model_name='propertyoffer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب'),
        ),
        migrations.AlterField(
            model_name='propertyoffer',
            name='floors',
            field=models.IntegerField(default=0, verbose_name='عدد الأدوار'),
        ),
        migrations.AlterField(
            model_name='propertyoffer',
            name='google_map',
            field=models.TextField(blank=True, null=True, verbose_name='موقع خرائط جوجل'),
        ),
        migrations.AlterField(
            model_name='propertyoffer',
            name='images_link',
            field=models.TextField(blank=True, null=True, verbose_name='رابط الصور'),
        ),
        migrations.AlterField(
            model_name='propertyoffer',
            name='listing_type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='نوع العرض'),
        ),
        migrations.AlterField(
            model_name='propertyoffer',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الحي'),
        ),
        migrations.AlterField(
            model_name='propertyoffer',
            name='owner_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم المالك'),
        ),
        migrations.AlterField(
            model_name='propertyoffer',
            name='owner_notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات المالك'),
        ),
        migrations.AlterField(
            model_name='propertyoffer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الجوال'),
        ),
        migrations.AlterField(
            model_name='propertyoffer',
            name='price',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='السعر'),
        ),
        migrations.AlterField(
            model_name='propertyoffer',
            name='property_age',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='عمر العقار'),
        ),
        migrations.AlterField(
            model_name='propertyoffer',
            name='property_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع العقار'),
        ),
        migrations.AlterField(
            model_name='propertyoffer',
            name='rooms',
            field=models.IntegerField(default=0, verbose_name='عدد الغرف'),
        ),
        migrations.AlterField(
            model_name='propertyoffer',
            name='status',
            field=models.CharField(choices=[('new', 'جديد'), ('under_review', 'قيد المراجعة'), ('approved', 'مقبول'), ('rejected', 'مرفوض'), ('published', 'تم نشره')], db_index=True, default='new', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='propertyoffer',
            name='video_link',
            field=models.TextField(blank=True, null=True, verbose_name='رابط الفيديو'),
        ),
        migrations.AlterField(
            model_name='propertyoffer',
            name='whatsapp_url',
            field=models.TextField(blank=True, null=True, verbose_name='رابط الواتساب'),
        ),
        migrations.AlterField(
            model_name='propertyrequestimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة'),
        ),
        migrations.AlterField(
            model_name='propertyrequestimage',
            name='is_cover',
            field=models.BooleanField(default=False, verbose_name='صورة الغلاف'),
        ),
        migrations.AlterField(
            model_name='propertyrequestimage',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.propertyoffer', verbose_name='الطلب'),
        ),
        migrations.AlterField(
            model_name='propertyrequestimage',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='ترتيب العرض'),
        ),
    ]
