# Generated by Django 6.0.2 on 2026-02-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0030_alter_property_options_alter_propertylead_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='show_price',
            field=models.BooleanField(default=True, verbose_name='إظهار السعر للزوار'),
        ),
    ]
