# Generated by Django 6.0.2 on 2026-02-28 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0031_property_show_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='show_price',
            new_name='show_price_to_visitors',
        ),
    ]
