# Generated by Django 6.0.2 on 2026-03-01 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0032_rename_show_price_property_show_price_to_visitors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(default='جدة', max_length=50, verbose_name='المدينة'),
        ),
    ]
