# Generated by Django 6.0.2 on 2026-03-01 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0033_alter_property_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='negotiation_status',
            field=models.CharField(blank=True, choices=[('قابل للتفاوض', 'قابل للتفاوض'), ('غير قابل للتفاوض', 'غير قابل للتفاوض'), ('على السوم', 'على السوم')], max_length=50, null=True, verbose_name='حالة السعر'),
        ),
    ]
