# Generated by Django 6.0.2 on 2026-03-01 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0034_property_negotiation_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertySmartLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=20, unique=True, verbose_name='الرمز الفريد')),
                ('views', models.IntegerField(default=0, verbose_name='عدد المشاهدات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='smart_link', to='listings.property', verbose_name='العقار')),
            ],
            options={
                'verbose_name': 'رابط ذكي',
                'verbose_name_plural': 'الروابط الذكية',
            },
        ),
    ]
