# Generated by Django 6.0.2 on 2026-03-01 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0035_propertysmartlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='FastRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الجوال')),
                ('request_text', models.TextField(verbose_name='نص الطلب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('is_read', models.BooleanField(default=False, verbose_name='مقروء')),
            ],
            options={
                'verbose_name': 'طلب سريع',
                'verbose_name_plural': 'الطلبات السريعة',
                'ordering': ['-created_at'],
            },
        ),
    ]
