# Generated by Django 6.0.2 on 2026-03-02 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0036_fastrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='رابط الفيديو (يوتيوب/تيك توك)'),
        ),
    ]
