# Generated by Django 6.0.2 on 2026-03-03 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0037_property_video_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم العميل')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الجوال')),
                ('property_type', models.CharField(choices=[('فيلا', 'فيلا'), ('شقة', 'شقة'), ('عمارة', 'عمارة'), ('دور', 'دور'), ('أرض', 'أرض'), ('مزرعة', 'مزرعة'), ('استراحة', 'استراحة'), ('محل تجاري', 'محل تجاري')], max_length=50, verbose_name='نوع العقار')),
                ('district', models.CharField(max_length=100, verbose_name='الحي')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='الميزانية')),
                ('status', models.CharField(choices=[('new', 'جديد'), ('matched', 'تم المطابقة'), ('contacted', 'تم التواصل'), ('closed', 'مغلق'), ('lost', 'مفقود')], db_index=True, default='new', max_length=20, verbose_name='الحالة')),
                ('source', models.CharField(blank=True, max_length=100, null=True, verbose_name='المصدر')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('match_score', models.FloatField(default=0.0, verbose_name='أعلى نسبة مطابقة')),
                ('matched_count', models.IntegerField(default=0, verbose_name='عدد العقارات المطابقة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to=settings.AUTH_USER_MODEL, verbose_name='مسند إلى')),
            ],
            options={
                'verbose_name': 'طلب عقار',
                'verbose_name_plural': 'طلبات العقارات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(verbose_name='نسبة المطابقة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ المطابقة')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_matches', to='listings.property', verbose_name='العقار')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='listings.propertyrequest', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'مطابقة عقار',
                'verbose_name_plural': 'مطابقات العقارات',
                'ordering': ['-score', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='propertyrequest',
            index=models.Index(fields=['property_type', 'district', 'budget'], name='listings_pr_propert_478f90_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyrequest',
            index=models.Index(fields=['status', 'match_score'], name='listings_pr_status_9b6c26_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='propertymatch',
            unique_together={('request', 'property')},
        ),
    ]
