# Generated by Django 6.0.2 on 2026-03-03 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0038_propertyrequest_propertymatch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyrequest',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='الميزانية'),
        ),
    ]
