# Generated by Django 6.0.2 on 2026-03-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0039_allow_null_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyrequest',
            name='apartments_count',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='عدد الشقق'),
        ),
        migrations.AddField(
            model_name='propertyrequest',
            name='area',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='المساحة المطلوبة'),
        ),
        migrations.AddField(
            model_name='propertyrequest',
            name='bathrooms_count',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='عدد دورات المياه'),
        ),
        migrations.AddField(
            model_name='propertyrequest',
            name='city',
            field=models.CharField(blank=True, default='جدة', max_length=50, null=True, verbose_name='المدينة'),
        ),
        migrations.AddField(
            model_name='propertyrequest',
            name='floors_count',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='عدد الأدوار'),
        ),
        migrations.AddField(
            model_name='propertyrequest',
            name='property_age',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='عمر العقار المفضل'),
        ),
        migrations.AddField(
            model_name='propertyrequest',
            name='request_type',
            field=models.CharField(blank=True, choices=[('شراء', 'شراء'), ('إيجار', 'إيجار')], max_length=20, null=True, verbose_name='نوع الطلب'),
        ),
        migrations.AddField(
            model_name='propertyrequest',
            name='rooms_count',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='عدد الغرف'),
        ),
        migrations.AddField(
            model_name='propertyrequest',
            name='usage_type',
            field=models.CharField(blank=True, choices=[('سكني', 'سكني'), ('تجاري', 'تجاري')], max_length=20, null=True, verbose_name='نوع الاستخدام'),
        ),
        migrations.AlterField(
            model_name='propertyrequest',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات إضافية'),
        ),
    ]
