# Generated by Django 6.0.2 on 2026-03-05 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0040_propertyrequest_apartments_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('فيلا', 'فيلا'), ('شقة', 'شقة'), ('عمارة', 'عمارة'), ('قصر', 'قصر'), ('دور', 'دور'), ('أرض', 'أرض'), ('مزرعة', 'مزرعة'), ('استراحة', 'استراحة'), ('محل تجاري', 'محل تجاري')], max_length=50, verbose_name='نوع العقار'),
        ),
        migrations.AlterField(
            model_name='propertyrequest',
            name='property_type',
            field=models.CharField(choices=[('فيلا', 'فيلا'), ('شقة', 'شقة'), ('عمارة', 'عمارة'), ('قصر', 'قصر'), ('دور', 'دور'), ('أرض', 'أرض'), ('مزرعة', 'مزرعة'), ('استراحة', 'استراحة'), ('محل تجاري', 'محل تجاري')], max_length=50, verbose_name='نوع العقار'),
        ),
    ]
