# Generated by Django 6.0.2 on 2026-03-05 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0041_alter_property_property_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='offer_type',
            field=models.CharField(choices=[('بيع', 'بيع'), ('إيجار', 'إيجار'), ('إستثمار', 'إستثمار')], max_length=20, verbose_name='نوع العرض'),
        ),
        migrations.AlterField(
            model_name='propertyrequest',
            name='request_type',
            field=models.CharField(blank=True, choices=[('شراء', 'شراء'), ('إيجار', 'إيجار'), ('إستثمار', 'إستثمار')], max_length=20, null=True, verbose_name='نوع الطلب'),
        ),
    ]
