# Generated by Django 6.0.2 on 2026-03-05 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0042_alter_property_offer_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('متاح', 'متاح'), ('مباع', 'مباع'), ('مؤجر', 'مؤجر'), ('قيد التفاوض', 'قيد التفاوض'), ('انتهت الفرصة', 'انتهت الفرصة')], default='متاح', max_length=20, verbose_name='الحالة'),
        ),
    ]
