# Generated by Django 6.0.2 on 2026-03-07 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0043_alter_property_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_start_date', models.DateField(blank=True, null=True, verbose_name='تاريخ بداية الصلاحية')),
                ('access_end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ نهاية الصلاحية')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access_profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'صلاحية دخول مستخدم',
                'verbose_name_plural': 'صلاحيات دخول المستخدمين',
            },
        ),
    ]
