# Generated by Django 6.0.2 on 2026-03-11 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0044_useraccessprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم العميل')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الجوال')),
                ('booking_date', models.DateField(verbose_name='تاريخ المعاينة')),
                ('booking_time', models.TimeField(verbose_name='وقت المعاينة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='listings.property', verbose_name='العقار')),
            ],
            options={
                'verbose_name': 'طلب حجز/معاينة',
                'verbose_name_plural': 'طلبات الحجز والمعاينة',
                'ordering': ['-created_at'],
            },
        ),
    ]
