# Generated by Django 6.0.2 on 2026-03-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0045_propertybooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_age',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='عمر العقار'),
        ),
    ]
