# Generated by Django 6.0.2 on 2026-03-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0046_alter_property_property_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='ad_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الإعلان'),
        ),
        migrations.AddField(
            model_name='property',
            name='val_license',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم رخصة فال'),
        ),
    ]
