# Generated by Django 6.0.2 on 2026-03-14 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0047_property_ad_number_property_val_license'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fastrequest',
            name='smart_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fast_requests', to='listings.propertysmartlink', verbose_name='الرابط الذكي المصدر'),
        ),
        migrations.AddField(
            model_name='propertylead',
            name='smart_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='listings.propertysmartlink', verbose_name='الرابط الذكي المصدر'),
        ),
        migrations.AddField(
            model_name='propertysmartlink',
            name='marketer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='smart_links', to=settings.AUTH_USER_MODEL, verbose_name='المسوق'),
        ),
        migrations.AlterField(
            model_name='propertysmartlink',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smart_links', to='listings.property', verbose_name='العقار'),
        ),
        migrations.AlterUniqueTogether(
            name='propertysmartlink',
            unique_together={('property', 'marketer')},
        ),
    ]
