# Generated by Django 6.0.2 on 2026-03-15 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0048_fastrequest_smart_link_propertylead_smart_link_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyoffer',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_offers', to=settings.AUTH_USER_MODEL, verbose_name='مسند إلى'),
        ),
        migrations.AlterField(
            model_name='propertyrequest',
            name='status',
            field=models.CharField(choices=[('new', 'جديد - غير معالج'), ('working', 'قيد العمل / في المهام'), ('contacted', 'تم التواصل مع العميل'), ('matched', 'تمت المطابقة'), ('closed', 'مغلق - تم الإنجاز'), ('lost', 'مفقود / غير جاد')], db_index=True, default='new', max_length=20, verbose_name='الحالة'),
        ),
    ]
