# Generated by Django 6.0.2 on 2026-03-15 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0049_propertyoffer_assigned_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyoffer',
            name='status',
            field=models.CharField(choices=[('new', 'جديد'), ('under_review', 'قيد المراجعة'), ('approved', 'مقبول'), ('rejected', 'مرفوض'), ('owner_review', 'مراجعة صاحب العقار'), ('published', 'تم نشره')], db_index=True, default='new', max_length=20, verbose_name='الحالة'),
        ),
    ]
