# Generated by Django 6.0.2 on 2026-03-15 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0050_alter_propertyoffer_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='propertylead',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL, verbose_name='مسند إلى'),
        ),
        migrations.AddField(
            model_name='propertylead',
            name='status',
            field=models.CharField(choices=[('new', 'جديد'), ('interested', 'عميل مهتم'), ('not_interested', 'عميل غير مهتم'), ('neutral', 'عميل محايد'), ('special_request', 'عميل له طلب خاص')], db_index=True, default='new', max_length=20, verbose_name='الحالة'),
        ),
    ]
