# Generated by Django 6.0.2 on 2026-04-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0058_propertyrequest_lead_score_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccessprofile",
            name="notification_email",
            field=models.EmailField(
                blank=True,
                help_text="يُستلم عليه تنبيهات الطلبات والإسناد. إن تُرك فارغاً يُستخدم بريد حساب المستخدم.",
                max_length=254,
                null=True,
                verbose_name="بريد التنبيهات",
            ),
        ),
    ]
