# Generated by Django 6.0.2 on 2026-04-08 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0059_useraccessprofile_notification_email'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='propertyrequest',
            new_name='listings_pr_propert_295f0c_idx',
            old_name='listings_pr_proptype_idx',
        ),
        migrations.RenameIndex(
            model_name='propertyrequest',
            new_name='listings_pr_distric_d5c282_idx',
            old_name='listings_pr_district_idx',
        ),
        migrations.RenameIndex(
            model_name='propertyrequest',
            new_name='listings_pr_budget_bf35f2_idx',
            old_name='listings_pr_budget_idx',
        ),
        migrations.RenameIndex(
            model_name='propertyrequest',
            new_name='listings_pr_source_fdc3dd_idx',
            old_name='listings_pr_source_idx',
        ),
        migrations.RenameIndex(
            model_name='propertyrequest',
            new_name='listings_pr_phone_59fa82_idx',
            old_name='listings_pr_dedup_fp_idx',
        ),
        migrations.AddField(
            model_name='propertysmartlink',
            name='inquiry_count',
            field=models.IntegerField(default=0, verbose_name='عدد الاستفسارات'),
        ),
    ]
