# Generated by Django 6.0.2 on 2026-04-08 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0060_rename_listings_pr_proptype_idx_listings_pr_propert_295f0c_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartLinkViewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='عنوان IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='برنامج المتصفح')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت المشاهدة')),
                ('smart_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_logs', to='listings.propertysmartlink', verbose_name='الرابط الذكي')),
            ],
            options={
                'verbose_name': 'سجل مشاهدة رابط ذكي',
                'verbose_name_plural': 'سجلات مشاهدات الروابط الذكية',
                'indexes': [models.Index(fields=['smart_link', 'ip_address', 'created_at'], name='listings_sm_smart_l_7167f7_idx')],
            },
        ),
    ]
