# Generated by Django 6.0.2 on 2026-04-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0064_useraccessprofile_staff_flags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccessprofile",
            name="allow_change_passwords",
            field=models.BooleanField(
                default=True,
                help_text="إن أُلغيَ التحديد: لا يمكنه تغيير كلمات المرور، ولا تعديل صلاحيات المستخدمين أو المجموعات أو ترقية حساب لموظف/مدير.",
                verbose_name="تغيير كلمات المرور والصلاحيات",
            ),
        ),
    ]
