# Generated by Django 6.0.2 on 2026-07-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0066_fastrequest_assigned_to'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='appointment',
            new_name='listings_ap_booking_607094_idx',
            old_name='listings_ap_booking_0471fb_idx',
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='listings_ap_status_11fb48_idx',
            old_name='listings_ap_status_96d682_idx',
        ),
        migrations.AlterField(
            model_name='property',
            name='image1',
            field=models.ImageField(blank=True, max_length=2000, null=True, upload_to='property_images/', verbose_name='صورة 1'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image10',
            field=models.ImageField(blank=True, max_length=2000, null=True, upload_to='property_images/', verbose_name='صورة 10'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image2',
            field=models.ImageField(blank=True, max_length=2000, null=True, upload_to='property_images/', verbose_name='صورة 2'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image3',
            field=models.ImageField(blank=True, max_length=2000, null=True, upload_to='property_images/', verbose_name='صورة 3'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image4',
            field=models.ImageField(blank=True, max_length=2000, null=True, upload_to='property_images/', verbose_name='صورة 4'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image5',
            field=models.ImageField(blank=True, max_length=2000, null=True, upload_to='property_images/', verbose_name='صورة 5'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image6',
            field=models.ImageField(blank=True, max_length=2000, null=True, upload_to='property_images/', verbose_name='صورة 6'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image7',
            field=models.ImageField(blank=True, max_length=2000, null=True, upload_to='property_images/', verbose_name='صورة 7'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image8',
            field=models.ImageField(blank=True, max_length=2000, null=True, upload_to='property_images/', verbose_name='صورة 8'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image9',
            field=models.ImageField(blank=True, max_length=2000, null=True, upload_to='property_images/', verbose_name='صورة 9'),
        ),
        migrations.AlterField(
            model_name='propertyrequestimage',
            name='image',
            field=models.ImageField(blank=True, max_length=2000, null=True, upload_to='property_requests/', verbose_name='الصورة'),
        ),
    ]
