# Generated by Django 6.0.2 on 2026-07-31 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0067_local_or_cloudinary_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteTicker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, help_text='فعّل لإظهار الشريط أسفل الهيدر في الواجهة.', verbose_name='إظهار الشريط')),
                ('label', models.CharField(blank=True, default='عاجل', help_text='مثال: عاجل، تنبيه، فرصة', max_length=40, verbose_name='وسم الشريط')),
                ('message', models.CharField(blank=True, default='', help_text='النص الذي يتحرك داخل الشريط.', max_length=500, verbose_name='نص التنبيه')),
                ('background_color', models.CharField(default='#1B4F9C', help_text='بصيغة HEX مثل #1B4F9C', max_length=7, verbose_name='لون الخلفية')),
                ('text_color', models.CharField(default='#FFFFFF', help_text='بصيغة HEX مثل #FFFFFF', max_length=7, verbose_name='لون الخط')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'شريط التنبيه المتحرك',
                'verbose_name_plural': 'شريط التنبيه المتحرك',
            },
        ),
    ]
