# Generated by Django 6.0.2 on 2026-07-31 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0068_site_ticker'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteAdBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, help_text='فعّل لإظهار البنر داخل قائمة العروض العقارية.', verbose_name='إظهار البنر')),
                ('image', models.ImageField(blank=True, help_text='ارفع تصميماً مناسباً للجوال والتابلت (مستحسن 1080×540 أو نسبة 2:1).', null=True, upload_to='ad_banners/', verbose_name='تصميم البنر')),
                ('link_url', models.URLField(blank=True, default='', help_text='اختياري — يفتح عند الضغط على البنر.', verbose_name='رابط عند الضغط')),
                ('alt_text', models.CharField(blank=True, default='الركن الأوسط للعقارات — تأجير · بيع · إدارة أملاك · تطوير عقاري', max_length=200, verbose_name='النص البديل')),
                ('insert_after', models.PositiveSmallIntegerField(default=3, help_text='مثال: 3 يعني بعد ثالث عقار في القائمة.', verbose_name='يظهر بعد كم عرض')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'البنر الإعلاني',
                'verbose_name_plural': 'البنر الإعلاني',
            },
        ),
    ]
