# Generated by Django 6.0.2 on 2026-07-31 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0069_site_ad_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyrequest',
            name='city',
            field=models.CharField(blank=True, default='الرياض', max_length=50, null=True, verbose_name='المدينة'),
        ),
        migrations.AlterField(
            model_name='propertyrequest',
            name='district',
            field=models.CharField(max_length=500, verbose_name='الحي / الأحياء'),
        ),
    ]
