# Generated by Django 6.0.2 on 2026-07-31 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0070_propertyrequest_district_len_riyadh'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('phone', models.CharField(max_length=30, verbose_name='الجوال')),
                ('subject', models.TextField(blank=True, default='', verbose_name='تفاصيل الطلب')),
                ('is_handled', models.BooleanField(default=False, verbose_name='تمت المتابعة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
            ],
            options={
                'verbose_name': 'رسالة تواصل',
                'verbose_name_plural': 'رسائل التواصل',
                'ordering': ['-created_at'],
            },
        ),
    ]
