# Generated by Django 6.0.2 on 2026-03-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketDailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='التاريخ')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت التوليد')),
                ('raw_snapshot', models.JSONField(help_text='جميع الصفوف المستخدمة في التحليل.', verbose_name='البيانات الخام (Snapshot)')),
                ('ai_report', models.TextField(blank=True, default='', verbose_name='تقرير الذكاء الاصطناعي')),
                ('succeeded', models.BooleanField(default=True, verbose_name='تم التوليد بنجاح')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='خطأ (إن وجد)')),
            ],
            options={
                'verbose_name': 'تقرير سوق يومي',
                'verbose_name_plural': 'تقارير السوق اليومية',
                'ordering': ['-date', '-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='RealEstateIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('جدة', 'جدة'), ('الرياض', 'الرياض')], db_index=True, max_length=20, verbose_name='المدينة')),
                ('neighborhood', models.CharField(db_index=True, max_length=120, verbose_name='الحي / المخطط')),
                ('date', models.DateField(db_index=True, verbose_name='التاريخ')),
                ('num_deals', models.PositiveIntegerField(default=0, verbose_name='عدد الصفقات')),
                ('total_value_sar', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='إجمالي القيمة (ريال)')),
                ('traded_area_sqm', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='المساحة المتداولة (م²)')),
                ('avg_price_per_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='متوسط سعر المتر')),
                ('avg_price_apartments', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='متوسط سعر المتر - شقق')),
                ('avg_price_lands', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='متوسط سعر المتر - أراضٍ')),
                ('avg_price_villas', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='متوسط سعر المتر - فلل')),
                ('avg_price_palaces', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='متوسط سعر المتر - قصور')),
                ('daily_change_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='التغيير اليومي ٪')),
                ('yearly_change_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='التغيير السنوي ٪')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات / تحليل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'مؤشر حي عقاري',
                'verbose_name_plural': 'مؤشرات الأحياء العقارية',
                'ordering': ['-date', 'city', '-num_deals'],
                'unique_together': {('city', 'neighborhood', 'date')},
            },
        ),
    ]
