# Generated by Django 6.0.2 on 2026-03-17 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketdailyreport',
            name='date',
            field=models.DateField(db_index=True, unique=True, verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='marketdailyreport',
            name='raw_snapshot',
            field=models.JSONField(blank=True, help_text='جميع الصفوف المستخدمة في التحليل.', null=True, verbose_name='البيانات الخام (Snapshot)'),
        ),
    ]
