# Generated by Django 6.0.2 on 2026-03-17 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_alter_marketdailyreport_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='realestateindex',
            options={'ordering': ['-date', 'city', '-num_deals'], 'verbose_name': 'مؤشر عقاري', 'verbose_name_plural': 'المؤشرات العقارية'},
        ),
        migrations.AlterUniqueTogether(
            name='realestateindex',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='realestateindex',
            name='period',
            field=models.CharField(choices=[('day', 'اليوم'), ('week', 'الأسبوع'), ('month', 'الشهر'), ('year', 'السنة')], default='day', max_length=10, verbose_name='الفترة'),
        ),
        migrations.AlterField(
            model_name='realestateindex',
            name='avg_price_per_m2',
            field=models.FloatField(default=0.0, verbose_name='متوسط سعر المتر'),
        ),
        migrations.AlterField(
            model_name='realestateindex',
            name='city',
            field=models.CharField(max_length=100, verbose_name='المدينة'),
        ),
        migrations.AlterField(
            model_name='realestateindex',
            name='date',
            field=models.DateField(verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='realestateindex',
            name='neighborhood',
            field=models.CharField(max_length=255, verbose_name='الحي'),
        ),
        migrations.AlterField(
            model_name='realestateindex',
            name='num_deals',
            field=models.IntegerField(default=0, verbose_name='عدد الصفقات'),
        ),
        migrations.AlterField(
            model_name='realestateindex',
            name='total_value_sar',
            field=models.FloatField(default=0.0, verbose_name='قيمة الصفقات'),
        ),
        migrations.AlterField(
            model_name='realestateindex',
            name='traded_area_sqm',
            field=models.FloatField(default=0.0, verbose_name='المساحة المتداولة'),
        ),
        migrations.RemoveField(
            model_name='realestateindex',
            name='avg_price_apartments',
        ),
        migrations.RemoveField(
            model_name='realestateindex',
            name='avg_price_lands',
        ),
        migrations.RemoveField(
            model_name='realestateindex',
            name='avg_price_palaces',
        ),
        migrations.RemoveField(
            model_name='realestateindex',
            name='avg_price_villas',
        ),
        migrations.RemoveField(
            model_name='realestateindex',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='realestateindex',
            name='daily_change_percent',
        ),
        migrations.RemoveField(
            model_name='realestateindex',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='realestateindex',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='realestateindex',
            name='yearly_change_percent',
        ),
    ]
