# Generated by Django 6.0.2

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_alter_realestateindex_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='realestateindex',
            unique_together={('city', 'neighborhood', 'date', 'period')},
        ),
    ]
