# Generated by Django 6.0.2 on 2026-03-18 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_alter_realestateindex_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketdailyreport',
            options={'ordering': ['-date', '-generated_at'], 'verbose_name': 'تقرير السوق', 'verbose_name_plural': 'تقارير السوق'},
        ),
        migrations.AlterUniqueTogether(
            name='realestateindex',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='realestateindex',
            name='property_type',
            field=models.CharField(choices=[('أرض', 'أرض'), ('شقة', 'شقة'), ('فيلا', 'فيلا')], default='أرض', max_length=50, verbose_name='نوع العقار'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='marketdailyreport',
            name='error_message',
            field=models.TextField(blank=True, default='', verbose_name='رسالة الخطأ'),
        ),
        migrations.AlterField(
            model_name='marketdailyreport',
            name='raw_snapshot',
            field=models.JSONField(blank=True, null=True, verbose_name='البيانات الخام'),
        ),
        migrations.AlterField(
            model_name='marketdailyreport',
            name='succeeded',
            field=models.BooleanField(default=True, verbose_name='تم بنجاح'),
        ),
        migrations.AlterUniqueTogether(
            name='realestateindex',
            unique_together={('city', 'neighborhood', 'date', 'period', 'property_type')},
        ),
    ]
