# Generated by Django 6.0.2 on 2026-03-19 00:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_alter_marketdailyreport_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(db_index=True, max_length=255)),
                ('city_name', models.CharField(blank=True, max_length=255, null=True)),
                ('avg_price', models.FloatField(default=0.0)),
                ('min_price', models.FloatField(default=0.0)),
                ('max_price', models.FloatField(default=0.0)),
                ('total_deals', models.IntegerField(default=0)),
                ('total_value', models.FloatField(default=0.0)),
                ('total_area', models.FloatField(default=0.0)),
                ('period', models.CharField(default='day', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='marketdailyreport',
            options={'ordering': ['-date', '-generated_at']},
        ),
        migrations.AlterModelOptions(
            name='realestateindex',
            options={'ordering': ['-date', 'city', '-num_deals']},
        ),
        migrations.AddField(
            model_name='realestateindex',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='marketdailyreport',
            name='ai_report',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='marketdailyreport',
            name='date',
            field=models.DateField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='marketdailyreport',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='marketdailyreport',
            name='generated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='marketdailyreport',
            name='raw_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marketdailyreport',
            name='succeeded',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='realestateindex',
            name='avg_price_per_m2',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='realestateindex',
            name='city',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='realestateindex',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='realestateindex',
            name='neighborhood',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='realestateindex',
            name='num_deals',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='realestateindex',
            name='period',
            field=models.CharField(choices=[('day', 'اليوم'), ('week', 'الأسبوع'), ('month', 'الشهر'), ('year', 'السنة')], default='day', max_length=10),
        ),
        migrations.AlterField(
            model_name='realestateindex',
            name='property_type',
            field=models.CharField(choices=[('land', 'أرض'), ('apartment', 'شقة'), ('villa', 'فيلا'), ('all', 'الكل')], default='all', max_length=20),
        ),
        migrations.AlterField(
            model_name='realestateindex',
            name='total_value_sar',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='realestateindex',
            name='traded_area_sqm',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddIndex(
            model_name='realestateindex',
            index=models.Index(fields=['city', 'date'], name='market_real_city_aef512_idx'),
        ),
        migrations.AddIndex(
            model_name='realestateindex',
            index=models.Index(fields=['neighborhood'], name='market_real_neighbo_1003b0_idx'),
        ),
        migrations.AddIndex(
            model_name='areastat',
            index=models.Index(fields=['area_name'], name='market_area_area_na_1805e8_idx'),
        ),
        migrations.AddIndex(
            model_name='areastat',
            index=models.Index(fields=['created_at'], name='market_area_created_ab56a6_idx'),
        ),
    ]
