# Generated by Django 6.0.2 on 2026-03-19 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_areastat_alter_marketdailyreport_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areastat',
            options={'ordering': ['-aggregation_date']},
        ),
        migrations.RemoveIndex(
            model_name='areastat',
            name='market_area_area_na_1805e8_idx',
        ),
        migrations.RemoveIndex(
            model_name='areastat',
            name='market_area_created_ab56a6_idx',
        ),
        migrations.AddField(
            model_name='areastat',
            name='aggregation_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='areastat',
            unique_together={('area_name', 'aggregation_date', 'period')},
        ),
        migrations.AddIndex(
            model_name='areastat',
            index=models.Index(fields=['area_name', 'aggregation_date'], name='market_area_area_na_856ae7_idx'),
        ),
    ]
