# Generated by Django 6.0.2 on 2026-03-19 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_alter_areastat_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_code', models.IntegerField(unique=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('city_name', models.CharField(max_length=100)),
                ('city_code', models.IntegerField()),
                ('region_name', models.CharField(max_length=100)),
                ('total_deals', models.IntegerField(default=0)),
                ('total_price', models.FloatField(default=0.0)),
                ('total_area', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-total_deals'],
            },
        ),
    ]
