# Generated by Django 6.0.2 on 2026-03-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='areastat',
            name='price_per_m2',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
