# Generated by Django 6.0.2 on 2026-03-19 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_areastat_price_per_m2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketdailyreport',
            name='ai_report',
        ),
    ]
