# Generated by Django 6.0.2 on 2026-04-08 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_remove_marketdailyreport_ai_report'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketdailyreport',
            options={'ordering': ['-date', '-generated_at'], 'verbose_name': 'تقرير يومي للبورصة', 'verbose_name_plural': 'التقارير اليومية للبورصة'},
        ),
        migrations.AlterModelOptions(
            name='realestateindex',
            options={'ordering': ['-date', 'city', '-num_deals'], 'verbose_name': 'مؤشر بورصة عقارية', 'verbose_name_plural': 'مؤشرات البورصة العقارية'},
        ),
    ]
