# Generated by Django 6.0.2 on 2026-04-26 08:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_key', models.CharField(db_index=True, help_text='قيمة فريدة لكل شركة/نسخة White-label (مثال: acme-realestate).', max_length=120, verbose_name='معرف الشركة')),
                ('provider', models.CharField(choices=[('haraj', 'حراج'), ('aqar', 'عقار'), ('x', 'X')], db_index=True, max_length=20, verbose_name='القناة')),
                ('name', models.CharField(default='default', help_text='اسم اختياري للإعداد إذا احتجت أكثر من إعداد للقناة نفسها.', max_length=120, verbose_name='اسم الإعداد')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='مفعل')),
                ('selectors', models.JSONField(blank=True, default=dict, help_text='قاموس selectors الخاص بالقناة (مثال: title_input, continue_button...).', verbose_name='Selectors')),
                ('settings_json', models.JSONField(blank=True, default=dict, help_text='إعدادات تشغيل البوت (timeouts, headless, step toggles...).', verbose_name='إعدادات إضافية')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_channel_configs', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة')),
            ],
            options={
                'verbose_name': 'إعداد قناة نشر',
                'verbose_name_plural': 'إعدادات قنوات النشر',
                'ordering': ['company_key', 'provider', '-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PublishingJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_key', models.CharField(db_index=True, max_length=120, verbose_name='معرف الشركة')),
                ('provider', models.CharField(choices=[('haraj', 'حراج'), ('aqar', 'عقار'), ('x', 'X')], db_index=True, max_length=20, verbose_name='القناة')),
                ('status', models.CharField(choices=[('pending', 'بانتظار التنفيذ'), ('running', 'قيد التنفيذ'), ('review_ready', 'جاهز للمراجعة'), ('succeeded', 'تم بنجاح'), ('failed', 'فشل'), ('cancelled', 'ملغي')], db_index=True, default='pending', max_length=20, verbose_name='الحالة')),
                ('source_model', models.CharField(blank=True, default='', max_length=120, verbose_name='الموديل المصدر')),
                ('source_object_id', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='معرف الكيان المصدر')),
                ('payload', models.JSONField(blank=True, default=dict, help_text='الـ payload القياسي الذي يتم تسليمه للـ adapter.', verbose_name='بيانات الإدخال')),
                ('result', models.JSONField(blank=True, default=dict, help_text='النتيجة النهائية/الوسيطة (review_url, external_id, artifacts...).', verbose_name='نتيجة التنفيذ')),
                ('error_details', models.JSONField(blank=True, default=dict, help_text='تفاصيل تقنية للخطأ عند الفشل.', verbose_name='تفاصيل الخطأ')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='عدد المحاولات')),
                ('max_attempts', models.PositiveIntegerField(default=3, verbose_name='الحد الأقصى للمحاولات')),
                ('priority', models.PositiveSmallIntegerField(db_index=True, default=5, verbose_name='الأولوية')),
                ('queued_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الإدراج بالطابور')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت بدء التنفيذ')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الانتهاء')),
                ('next_retry_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='موعد إعادة المحاولة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('channel_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='publishing.channelconfig', verbose_name='إعداد القناة المستخدم')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publishing_jobs', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
            ],
            options={
                'verbose_name': 'مهمة نشر',
                'verbose_name_plural': 'مهام النشر',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='channelconfig',
            index=models.Index(fields=['company_key', 'provider', 'is_active'], name='publishing__company_a07ca2_idx'),
        ),
        migrations.AddConstraint(
            model_name='channelconfig',
            constraint=models.UniqueConstraint(fields=('company_key', 'provider', 'name'), name='uq_channel_config_company_provider_name'),
        ),
        migrations.AddIndex(
            model_name='publishingjob',
            index=models.Index(fields=['company_key', 'provider', 'status'], name='publishing__company_952f51_idx'),
        ),
        migrations.AddIndex(
            model_name='publishingjob',
            index=models.Index(fields=['status', 'next_retry_at'], name='publishing__status_a5e8fe_idx'),
        ),
        migrations.AddIndex(
            model_name='publishingjob',
            index=models.Index(fields=['source_model', 'source_object_id'], name='publishing__source__7f9874_idx'),
        ),
    ]
